version: '3'

services:
  prometheus-af-south-1:
    image: prom/prometheus
    container_name: prom_1
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus-af-south-1.yml:/etc/prometheus/prometheus.yml
    

  prometheus-eu-west-1:
    image: prom/prometheus
    container_name: prom_2
    ports:
      - "9091:9090"
    volumes:
      - ./prometheus/prometheus-eu-west-1.yml:/etc/prometheus/prometheus.yml

  prometheus-eu-west-3:
    image: prom/prometheus
    container_name: prom_3
    ports:
      - "9092:9090"
    volumes:
      - ./prometheus/prometheus-eu-west-3.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: Grafana_dashboards
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning


    


