global:
  scrape_interval: 15s

scrape_configs:
  - job_name: '4-sure Ireland servers'
    ec2_sd_configs:
      - region: 'eu-west-1'
    static_configs:
      - targets: ['54.220.68.144:9100', '52.19.139.59:9100']
