global:
  scrape_interval: 15s

scrape_configs:
  - job_name: '4-sure Capetown servers'
    ec2_sd_configs:
      - region: 'af-south-1'
    static_configs:
      - targets: ['174.129.126.46:9100', '54.220.68.144:9100']
